[package]
name = 'moran'
publish = false
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'moran'

[dependencies]
extendr-api = { version = "0.7", features = ["faer"] }
faer = { version = "0.19", features = ["rand"] }

[profile.release]
lto = true
codegen-units = 1