# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_moran_wrappers", use_symbols = TRUE, package_name = "moran")

#' @usage NULL
#' @useDynLib moran, .registration = TRUE
NULL

#' @export
mem <- function(x) .Call(wrap__mem, x)


# nolint end
